openapi: 3.0.3
info:
  title: Manatee API
  version: 1.0.0
  description: |
    Candidate application management API codenamed "Manatee" is a mockup of a real system,
    where recruiters can view new applications and follow a process until successful onboarding.  

servers:
  - url: http://localhost:8080/
    description: Local development server

externalDocs:
  url: https://swagger.io/specification/
  description: Find more information about OAS3.0 standard.

tags:
  - name: Application
    description: API for services related application management.

paths:
  /applications:
    get:
      operationId: getApplications
      tags:
        - Application
      summary: Queries all applications.
      description: Selects all applications stored in database and returns them as an array.
      responses:
        '200':
          description: Successful query returns an array of applications.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Application'    
    post:
      operationId: addApplication
      tags:
        - Application
      summary: Submits new applications.
      description: Submits a new applications and instantiates it with a new state.
      requestBody:
        description: A new application information.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
      responses:
        '201':
          description: Successfully submitted applications returns an instance with given id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
  
  /applications/scheduled:
    get:
      operationId: getApplicationInterviews
      tags:
        - Application
      summary: Queries all interviews scheduled for submitted applications.
      description: Selects all interviews scheduled for submitted applications that is stored in database and returns them as an array.
      responses:
        '200':
          description: Successful query returns an array of interviews for all applications.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Interview'

  /applications/{applicationId}:
    patch:
      operationId: rejectApplication
      tags:
        - Application
      summary: Rejects an applications with given Id.
      description: Find the applications and performs a state transition to rejected state.
      parameters:
        - $ref: '#/components/parameters/ApplicationId'
      responses:
        '202':
          description: Application rejection was accepted and state transition was successful.

  /applications/{applicationId}/interview/:
    post:
      operationId: scheduleInterview
      tags:
        - Application
      summary: Schedules an interview for an application with given Id.
      description: Creates and interview and links it with an application. The application must exists before scheduling an interview.
      parameters:
        - $ref: '#/components/parameters/ApplicationId'
      requestBody:
        description: New interview information. Contains the datetime for the interview.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Interview'
      responses:
        '201':
          description: Successfully submitted applications returns an instance with given id.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Interview'
        '404':
          description: Application is not found.

  


components:
  schemas:
    Application:
      type: object
      required:
        - candidate
      properties:
        id:
          type: integer
        applicationState:
          $ref: '#/components/schemas/ApplicationState'
        candidate:
          $ref: '#/components/schemas/Candidate'
        updatedOn:
          type: string
          format: date-time

    Candidate:
      type: object
      required:
        - firstName
        - lastName
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string

    Interview:
      type: object
      required:
        - time
      properties:
        id:
          type: integer
        application:
          $ref: '#/components/schemas/Application'
        time:
          type: string
          format: date-time

    ApplicationState:
      type: string
      enum:
        - New
        - Interview
        - Offer
        - Pre-onboard
        - Hired
        - Rejected

  parameters:
    ApplicationId:
      name: applicationId
      in: path
      description: ID of application to use
      required: true
      schema:
        type: integer
    InterviewId:
      name: interviewId
      in: path
      description: ID of interview to use
      required: true
      schema:
        type: integer
    InterviewQuery:
      name: interview
      in: query
      description: Filter applications based on whether they have interviews scheduled
      required: false,
      schema:
        type: boolean
    
